FROM python:3.12.10-slim

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y --no-install-recommends gcc libc-dev && \
    pip install --no-cache-dir -r requirements.txt
COPY . .

EXPOSE 8000

CMD ["python", "product_service.py"]